/** Generated from schema.json; defend wire compatibility (ADR 0006). Do not edit. */
import type * as Evaluator from '../../contracts/evaluator/types.ts';
export type Mount = { "source": string; "path": string; "mode": "ro" | "rw"; "maximumBytes"?: number; [key: string]: unknown; };
export type Revision = { "plan": { "name": string; "version": string; "entry": string; "args": (string)[]; "cwd": string; "execution"?: "source" | "artifacts"; "network"?: "none" | "egress"; [key: string]: unknown; }; "pins": { [key: string]: { "source": string; "hash": string; "mount": string; [key: string]: unknown; }; }; "mounts": (Mount)[]; "stateMount": string; "endpointMount": string; "socketName": string; "quotaBytes": number; "formats": ({ "path": string; "schema": { [key: string]: unknown; }; [key: string]: unknown; })[]; "migrations": ({ "entry": string; "args": (string)[]; [key: string]: unknown; })[]; "migrate": "stop" | "shared"; [key: string]: unknown; };
export type Principal = { "id": string; "role": "admin" | "reviewer" | "user"; "projects": (string)[]; "observeOthers": boolean; [key: string]: unknown; };
export type Identity = { "people": (Principal)[]; "bindings": ({ "kind": string; "id": string; "person": string; [key: string]: unknown; })[]; "authorities": { [key: string]: string; }; [key: string]: unknown; };
export type Target = { "id": string; "owner": string; "scope": "person" | "deployment"; "state": string; "profile": { [key: string]: unknown; }; "entries": ({ [key: string]: unknown; })[]; "services": (string)[]; "registration"?: { "package": string; "id": string; [key: string]: unknown; }; "environment"?: boolean; "revision": Revision; [key: string]: unknown; };
export type Deployment = { "version": 1; "root": string; "cgroup": string; "identity": Identity; "targets": (Target)[]; "bootstrap"?: Bootstrap; "trusted"?: Trusted; "work"?: (Work)[]; [key: string]: unknown; };
export type Bootstrap = { "recipe": string; "registry": string; "cache": string; "output": string; "profile": string; "discoveryRoot": string; [key: string]: unknown; };
export type Release = { "digest": string; "targets": (Target)[]; [key: string]: unknown; };
export type Trusted = { "origin": string; "socket": string; "keyFd": number; "administrator": string; "baseline": number; "digest": string; "releases": (Release)[]; "plans": ({ "source": string; "plan": Evaluator.Plan; [key: string]: unknown; })[]; "execution"?: (Execution)[]; [key: string]: unknown; };
export type Work = { "target": string; "root": string; "cache": string; "discoveryRoot": string; "discoveryEntry": string; [key: string]: unknown; };
export type ExecutionArm = { "plan": { "name": string; "version": string; "entry": string; "args": (string)[]; "cwd": string; "execution"?: "source" | "artifacts"; "network"?: "none" | "egress"; "mounts": (Mount)[]; [key: string]: unknown; }; "setup": { [key: string]: unknown; }; "pins": { [key: string]: { "source": string; "hash": string; [key: string]: unknown; }; }; [key: string]: unknown; };
export type ExecutionFixture = { "source": string; "hash": string; "checks": { [key: string]: { "path": string; "hash": string; [key: string]: unknown; }; }; [key: string]: unknown; };
export type Execution = { "source": string; "account": string; "services": (string)[]; "startup": Evaluator.Startup; "arms": { [key: string]: ExecutionArm; }; "fixtures": { [key: string]: ExecutionFixture; }; "privateRoots": (string)[]; [key: string]: unknown; };
export type Contract = Deployment;
